name: icon-automation

on:
  push:
    branches:
      - master
    paths:
      - package.json

jobs:
  icon_automation:
    name: Figma Icon Automation
    runs-on: ubuntu-latest
    steps:
      # Checkout repository
      - uses: actions/checkout@v3

      # Setup Node.js (modern LTS version)
      - uses: actions/setup-node@v3
        with:
          node-version: "20"

      # Update CA certificates to fix SSL issues
      - name: Update CA certificates
        run: sudo apt-get update && sudo apt-get install --reinstall ca-certificates

      # Optional: Cache Yarn dependencies for faster builds
      - name: Cache Yarn dependencies
        uses: actions/cache@v3
        with:
          path: ~/.yarn/cache
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      # Set Yarn registry to avoid potential SSL issues
      - name: Set Yarn registry
        run: yarn config set registry https://registry.npmjs.org/

      # Install dependencies
      - name: Install dependencies
        run: yarn install

      # Run Figma Action
      - name: Figma Action
        uses: primer/figma-action@v1.0.0-alpha.2
        with:
          args: "format=svg outputDir=./src/"
        env:
          FIGMA_FILE_URL: ${{ secrets.FIGMA_FILE_URL }}
          FIGMA_TOKEN: ${{ secrets.FIGMA_TOKEN }}

      # Generate files
      - name: Generate
        run: yarn generate

      # Build bundle
      - name: Build Bundle
        run: yarn build:bundle

      # Setup npm auth for publishing
      - name: Setup npm auth
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_AUTH_TOKEN }}" > ~/.npmrc

      # Publish package
      - name: Publish
        run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

      # Build the project
      - name: Build
        run: yarn build

      # Deploy to GitHub Pages
      - name: GitHub Pages
        uses: crazy-max/ghaction-github-pages@v1.2.5
        with:
          build_dir: docs
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
